vim.cmd("so ~/.config/nvim/old_rc.vim")
local socket = vim.api.nvim_exec("echo serverstart('nvim.sasock')", true)
home=os.getenv( "HOME" )
file = io.open(home .. "/.config/nvim/.nvim.sock", "w+")
file:write(socket)
file:close()
